name: CI

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person Name'     
        required: true
        default: 'Kate'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello: ${{ github.event.inputs.name }}"
